version: "3"
services:
  application:
      image: spring-boot-mysql-app
      ports:
        - "8080:8080"
      networks:
        - "springboot-mysql-net"
      depends_on:
        - "mysqldb"
      volumes:
        - "/data/springboot-app"     
  mysqldb:
      image: mysql:5.7
      networks:
       - "springboot-mysql-net"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASES=sbms
      volumes:
        - /data/mysql
networks:
  springboot-mysql-net:
  
